### ISSUE TITLE
ActiveSupport::MessageEncryptor::InvalidMessage

### ISSUE THREAD

**Issue by natusdrew** [natusdrew/rails-templates#5]
**Describe the bug**
A problem with the encrypted credentials

ActiveSupport::MessageEncryptor::InvalidMessage 

**To Reproduce**
1. Command: rails s

**Expected behavior**
run the rails server

**Comment by lizateaches** [comment]
Is the master key in the project?

**Comment by tinyshelley9** [comment]
run ```rails c``` and see if you can check for existing env vars and such

**Comment by natusdrew** [comment]
master.key changes and cannot derypt the original credentials.yml.enc file

https://github.com/rails/rails/issues/31397
